app = "spiritsbox"  # Usa el nombre exacto creado en Fly.io

[build]
  builder = "paketobuildpacks/builder:base"

[env]
  PORT = "8080"

[[services]]
  internal_port = 8080
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

    [vm]
    size = "shared-cpu-1x"  # 🧠 1 CPU
    memory = 256            # o 256 si necesitas menos